#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    hass --config "${PWD}/config" --script ensure_config
    # Bind to 0.0.0.0 for mobile testing
    echo -e "\nhttp:\n  server_host: 0.0.0.0" >> "${PWD}/config/configuration.yaml"
    wget -O - https://get.hacs.xyz | bash -
fi

#  Install meteo-overview card
CARD_HA_DIR="${PWD}/config/www/community/meteo-overview"
CARD_DIST_DIR="${PWD}/dist"
rm -rf "${CARD_HA_DIR}"
mkdir -p "${CARD_HA_DIR}"
cp "${CARD_DIST_DIR}/"* "${CARD_HA_DIR}/";
# watch for changes in dist and copy to HA www dir
( \
    while inotifywait -qq -e modify,create "${CARD_DIST_DIR}"; \
        do cp "${CARD_DIST_DIR}/"* "${CARD_HA_DIR}/"; \
    done
) &


# Register the card as a dashboard resource
mkdir -p "${PWD}/config/.storage"
cp "${PWD}/scripts/lovelace_resources.json" "${PWD}/config/.storage/lovelace_resources"


echo "Starting Home Assistant in development mode...
    - Custom component mounted at /config/custom_components/meteoclub
    - Access UI at http://localhost:8123
    - For mobile testing, use your host machine's IP on port 8123

    "

# Start Home Assistant
hass --config "${PWD}/config" --debug