#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    hass --config "${PWD}/config" --script ensure_config
    # Bind to 0.0.0.0 for mobile testing
    echo -e "\nhttp:\n  server_host: 0.0.0.0" >> "${PWD}/config/configuration.yaml"
    wget -O - https://get.hacs.xyz | bash -
    mkdir -p "${PWD}/config/www/community"
    ln -s "${PWD}"/dist" "${PWD}/config/www/community/meteo-overview"
fi

echo "Starting Home Assistant in development mode...
    - Custom component mounted at /config/custom_components/meteoclub
    - Access UI at http://localhost:8123
    - For mobile testing, use your host machine's IP on port 8123

    "

# Start Home Assistant
hass --config "${PWD}/config" --debug